version: '3'
services:
  lb:
    image: dockercloud/haproxy
    links:
      - prerender
    ports:
      - 8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prerender:
    build: .
    privileged: true
    links:
      - redis
    environment:
      - 'REDIS_URL=redis://redis:6379/0'

  redis:
    image: redis:alpine
    ports:
      - 6380:6379
